import { expect, test } from '@playwright/test'

test('payments tab renders seeded PayPal sandbox data', async ({ page }) => {
  await page.goto('/payments-preview')
  await expect(page.getByTestId('mock-data-banner')).toHaveText('MOCK DATA')
  await expect(page.getByTestId('paypal-sandbox-badge')).toHaveText('PayPal Sandbox')
  await expect(page.getByText('Kickoff')).toBeVisible()
  await expect(page.getByText('USD 12000.00')).toBeVisible()
  await expect(page.getByTestId('mandate-hash')).not.toHaveText('Mandate not hashed yet')
  await expect(page.getByRole('button', { name: 'Copy hash' })).toBeEnabled()
  await expect(page.getByText('Allowed · create_invoice')).toBeVisible()
  await expect(page.getByText(/Blocked ·/)).toBeVisible()
  await expect(page.getByText(/Needs approval/)).toBeVisible()
  await expect(page.getByRole('row', { name: /Kickoff/ }).getByRole('button', { name: 'Approve' })).toHaveCount(0)
  await expect(page.getByRole('row', { name: /Bonus/ }).getByRole('button', { name: 'Approve' })).toBeVisible()
  await expect(page.getByText('PAID').first()).toBeVisible()
  await expect(page.getByText('REFUNDED').first()).toBeVisible()
  await expect(page.getByText('PARTIALLY_REFUNDED').first()).toBeVisible()
  await expect(page.getByText('PayPal webhook').first()).toBeVisible()
  await expect(page.getByText('owner@lexproof.demo').first()).toBeVisible()
  await expect(page.getByText(/approved by Blair Approver/)).toBeVisible()
  await expect(page.getByTestId('receipts').locator('li').first()).toContainText('2026-10-06T13:32:00Z')
  await expect(page.getByTestId('receipt-hash').first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open in PayPal Sandbox' }).first()).toHaveAttribute('href', /sandbox\.paypal\.com/)
  await expect(page.getByText('PayPal error · MISSING_RECIPIENT_EMAIL')).toBeVisible()
})
